### ISSUE TITLE
unknown type name 'uint32_t'

### ISSUE THREAD

**Issue by Maphardam** [deuill/go-php#24] opened 2016-06-20 13:11 UTC
When I try to go-get `go-php`, I'm receiving the following error:

```
workspace/src/github.com/deuill/go-php/engine/context.c: In function ‘context_eval’:
workspace/src/github.com/deuill/go-php/engine/context.c:71:2: error: unknown type name ‘uint32_t’
  uint32_t compiler_options = CG(compiler_options);
  ^
```
My gcc version is 4.8.5.
I'm not familiar with C, so I'd be glad if you could help me to solve my issue.

**Comment by deuill** [comment] 2016-06-20 17:04
Hi @Maphardam, what distro and version of PHP are you trying to build against? If you're building against PHP7, can you confirm you're passing the correct build tag (i.e. `go get  -tags php7 github.com/deuill/go-php`).

I'm on GCC version 6.1.1, so it may be that there's an include missing, or an issue with compiling against GCC 4.x, which I'll try to confirm, but the above information would help in the meanwhile.

**Comment by Maphardam** [comment] 2016-06-20 18:25
Hi @deuill ,
thank you for your response.
My distribution is CentOS 7 x86-64, on kernel 3.10.
My PHP version is 5.4.16, so I've just called `go get github.com/deuill/go-php`

I also assume, that in older versions of GCC the library ''stdint.h`/`cstdint` is missing.

**Comment by deuill** [comment] 2016-06-20 18:26
Yeah, sounds like it. I'll run some tests and open a pull request you can check.

**Comment by deuill** [comment] 2016-06-20 19:58
Hi @Maphardam, check #25 out and tell me if it works for you. I'm not merging this yet because I'm getting test failures on the `TestContextLog` test, and want to get a better picture of why it's failing.

I know PHP 5.4 is the default on the Amazon AMIs (which I assume is what you're trying to build on), but I believe PHP 5.5 and PHP 5.6 are also available (under the `php55-embedded` and `php56-embedded` packages), which may give you better mileage. I haven't really tested `go-php` under anything other PHP 5.6 and PHP 7, so you may get undiscovered bugs in weird places.

I'll see about getting Travis up and running in order to test against older versions of PHP, since manual testing is a massive chore.

**Comment by Maphardam** [comment] 2016-06-22 11:14
Hey,
thank you for your patch. Using it solves indeed the error described above.
I'm now left with problems regarding the libphp5.so location, but this is most likely due to my compiler settings, not a bug of your software.

Thank you again for your help.

**Comment by deuill** [comment] 2016-06-22 11:59
@Maphardam it may be that you're missing the actual library, make sure you have the `php54-embedded` package installed.

**Comment by deuill** [comment] 2016-06-22 14:48
Adding the additional search path on [this file](https://github.com/deuill/go-php/blob/daf6987b14a969e3935127753e0a4cec6c3fd768/engine/php5.go#L7) (as `-L/usr/lib64/httpd/modules/`) might work.

However I am still under the impression that the PHP library isn't usually shipped along with the binaries and should be in a seperate package (or at least, it's not the case on the Amazon AMIs I use, which are based on CentOS, nor on Debian or Archlinux). I've been wrong before though, so ehm.

**Comment by deuill** [comment] 2016-07-11 22:35
Closing this, please open a new ticket if the issue isn't resolved for you. I'm keeping the PR open and unmerged while I decide on whether implementing PHP 5.4/GCC 4.8 support is of any benefit, since it's pretty hard to test going forward (unless I can get Travis set up).

**Closed by deuill** 2016-07-11 22:35 UTC
Labels: bug

**Comment by Maphardam** [comment] 2016-07-12 08:28
Hey @deuill ,
I'm sorry for not responding before. I dropped the project due to time constraints and couldn't focus on this issue anymore.
